version: "3.9"
services:
  node:
    image: sdc-node
    container_name: sdc-node
    ports:
      - 3000:3000
    build:
      context: ./backend
      dockerfile: node.Dockerfile
  postgres:
    image: sdc-postgres
    container_name: "sdc-postgres"
    ports:
      - 3001:5432
    environment: 
      POSTGRES_USER: "jordant."
      POSTGRES_PASSWORD: "jordant"      
    build:
      context: .
      dockerfile: postgres.Dockerfile
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 4747:4747 
    build:
      context: .
      dockerfile: nginx.Dockerfile
